config/routes.rb
Rails.application.routes.draw do

  resources :image_sliders
  resources :sliders
  resources :sobres
  resources :contatos
  resources :image_services

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      },:path => 'u'

  resources :states
  resources :cities
  resources :comments
  resources :services
  resources :users
  resources :categories

  get 'comments/novo/:id', to:'comments#new', as: 'novo_comentario'

  get 'home/index', to:'users#index', as:'mostrar_servico'

  get 'users/show/:id', to:'users#destacar', as:'destacar_usuario'

  get 'users/novo/:id', to:'users#change', as: 'mostrar_usuario'

  get 'users/show', to:'users#desactive', as: 'desactive_usuario'

  get 'comments/report/:id', to:'users#report', as: 'report_comentario'

  #TELA INICIAL - Escolha das cidades
  root to: 'tela_inicial#index'  
  get '/tela_inicial/:alterar', to:'tela_inicial#index', as: 'alterar_cidade'
  
  #TELA DE INICIO - CATEGORIAS, FOTOS, COMENTARIOS
  post 'home', to: 'home#index'
  get 'home', to: 'home#index'
  post 'busca', to: 'home#busca'
  get 'busca/:id', to: 'home#busca', as: "busca_category_id"
  get 'home/professional/:id', to: 'home#show_professional', as: "show_professional"
  get 'home/service/:id', to: 'home#show_service', as: "show_service"

  #PAINEL DO USUARIO
  get 'painel', to: 'painel#index'

  
end

app/models/category.rb
class Category < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	mount_uploader :foto, FotoUploader
	#Status : 0 (Ativo) e 1 (Inativo)
	enum status: [:ativo, :inativo]
	has_many :users
end

app/models/city.rb
class City < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :state
  has_many :users

  def city_state
  	 "#{name} - #{state.name}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :service
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/image_service.rb
class ImageService < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	belongs_to :service

	mount_uploader :avatar, AvatarUploader
end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord
	
	require 'carrierwave/orm/activerecord'

	belongs_to :slider

	mount_uploader :figure, FigureUploader

end

app/models/service.rb
class Service < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :comments, dependent: :destroy
  has_many :image_services, dependent: :destroy
  belongs_to :user_client, class_name: 'User', :foreign_key => 'user_client_id'
  belongs_to :user_professional, class_name: 'User', :foreign_key => 'user_professional_id'

  accepts_nested_attributes_for :image_services, reject_if: :all_blank, allow_destroy: true
end

app/models/slider.rb
class Slider < ApplicationRecord
	has_many :image_sliders, dependent: :destroy

	accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :cities
end

app/models/user.rb
class User < ApplicationRecord

  require 'carrierwave/orm/activerecord'

  mount_uploader :perfil, PerfilUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  enum kind: [:cliente, :professional, :administrator]
  belongs_to :city
  belongs_to :category
  has_many :services



  def active_for_authentication? 
    super && status=='ativo'
    :approved
  end 

  def inactive_message 
    if status=='inativo'
      :not_approved 
    else 
      super
    end 
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  require 'will_paginate/array'

  before_action :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    
      @q = Service.ransack(params[:q])
      @services_professional = @q.result(distinct: true).where(user_professional_id: current_user.id)
      @services_professional = @services_professional.paginate(:page => params[:page], :per_page => 8)

      @q = Service.ransack(params[:q])
      @services_cliente = @q.result(distinct: true).where(user_client_id: current_user.id)
      @services_cliente = @services_cliente.paginate(:page => params[:page], :per_page => 8)

      @q = Service.ransack(params[:q])
      @services_admin = @q.result(distinct: true)
      @services_admin = @services_admin.paginate(:page => params[:page], :per_page => 8)

  end

  # GET /services/1
  # GET /services/1.json
  def show

    @services = Service.where(id: params[:id].to_i)

    @comments_aux = Comment.all
    @comments = Array.new

    @services.each do |service|
      @comments_aux.each do |comment|
        if comment.service_id==service.id
          @comments.push(comment)
        end
      end
    end

    @comments = @comments.paginate(:page => params[:page], :per_page => 4)
    
    @photos = Array.new

    @todas = ImageService.all

    @todas.each do |cada|
      if cada.service_id==params[:id].to_i 
        @photos.push(cada)
      end
    end

  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create

    @service = Service.new(service_params)
    @service.user_professional_id = current_user.id

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:description, :user_client_id, :user_professional_id, :status, :image_services_attributes => [:id, :avatar, :service_id, :_destroy])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sobres_helper.rb
module SobresHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/services/_form.html.erb
<%= form_for @service, :html => { :class => "form-horizontal service" } do |f| %>

  <% if @service.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <p>

    <%= link_to_add_association('Adicionar imagem', f, :image_services, 'data-association-insertion-node' => "#list-image ol", 'data-association-insertion-method' => "append", :class => 'button-xs') %>

  </p>

  <fieldset id="list-image">

    <ol>

      <%= f.fields_for :image_services do |image| %>

        <%= render partial: "image_service_fields", locals: {f: image} %>

        <% end %>

    </ol>

  </fieldset>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    
    <%= f.label :user_client_id, :class => 'control-label col-lg-2' %>
    
    <div class="col-lg-10">
    
    <%= f.collection_select(:user_client_id, User.where(status: "ativo", kind: "cliente"),
                  :id, :name,
                 {:prompt => "Selecione o cliente"}) %>

    </div>

    <%=f.error_span(:user_client_id) %>
  </div>
  
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :status, options_for_select([["Ativo", "ativo"], ["Inativo", "inativo"]]),{}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                services_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/services/_image_service_fields.erb
<li class="control-group nested-fields">

	<div class="controls">

	    <div class="controls">
	    <%= f.label :avatar %>
	    <%= image_tag(f.object.avatar_url(:thumb)) if f.object.avatar? %>
    	<%= f.file_field :avatar, :cols => "20", :rows => "10" %>
	    </div>

	  	<div class="controls">
    		<%= link_to_remove_association "Remover", f %>
  		</div>

	</div>

</li>

app/views/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/services/index.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= search_form_for @q do |f| %>
          <div>
            <%= f.search_field :description_cont, placeholder: 'Nome' do %>
            <% end %>
            <%= f.submit 'Procurar' %>
          </div>
<% end %>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_client_id) %></th>
      <th><%= model_class.human_attribute_name(:user_professional_id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <% if current_user.kind=="professional" %>

  <tbody>
    <% @services_professional.each do |service| %>
      <tr>
        <td><%= link_to service.id, service_path(service) %></td>
        <td><%= service.description %></td>
        <td><%= service.user_client.name %></td>
        <td><%= service.user_professional.name %></td>
        <td><%= service.status %></td>
        <td><%=l service.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      service_path(service), :class => 'btn btn-default btn-xs' %>

          <% if policy(:user).updateService? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_path(service), :class => 'btn btn-default btn-xs' %>
          <% end %>

          <% if policy(:user).destroyService? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_path(service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>

          <% if policy(:user).createComment? %>
              <%= link_to "Comentar",
                          novo_comentario_path(service.id),
                          :class => 'btn btn-primary btn-xs' %>
          <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>

  <% end %>

  <% if current_user.kind=="cliente" %>

  <tbody>
    <% @services_cliente.each do |service| %>
      <tr>
        <td><%= link_to service.id, service_path(service) %></td>
        <td><%= service.description %></td>
        <td><%= service.user_client.name %></td>
        <td><%= service.user_professional.name %></td>
        <td><%= service.status %></td>
        <td><%=l service.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      service_path(service), :class => 'btn btn-default btn-xs' %>

          <% if policy(:user).updateService? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_path(service), :class => 'btn btn-default btn-xs' %>
          <% end %>

          <% if policy(:user).destroyService? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_path(service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>

          <% if policy(:user).createComment? %>
              <%= link_to "Comentar",
                          novo_comentario_path(service.id),
                          :class => 'btn btn-primary btn-xs' %>
          <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>

  <% end %>

  <% if current_user.kind=="administrator" %>

  <tbody>
    <% @services_admin.each do |service| %>
      <tr>
        <td><%= link_to service.id, service_path(service) %></td>
        <td><%= service.description %></td>
        <td><%= service.user_client.name %></td>
        <td><%= service.user_professional.name %></td>
        <td><%= service.status %></td>
        <td><%=l service.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      service_path(service), :class => 'btn btn-default btn-xs' %>

          <% if policy(:user).updateService? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_path(service), :class => 'btn btn-default btn-xs' %>
          <% end %>

          <% if policy(:user).destroyService? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_path(service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>

          <% if policy(:user).createComment? %>
              <%= link_to "Comentar",
                          novo_comentario_path(service.id),
                          :class => 'btn btn-primary btn-xs' %>
          <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>

  <% end %>

</table>

<% if policy(:user).createService? %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_service_path,
            :class => 'btn btn-primary' %>

<% end %>

<%= will_paginate @services_professional, renderer: BootstrapPagination::Rails %>
<%= will_paginate @services_admin, renderer: BootstrapPagination::Rails %>
<%= will_paginate @services_cliente, renderer: BootstrapPagination::Rails %>

app/views/services/new.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/services/show.html.erb
<%= link_to t('.back', :default => t("helpers.links.back")),
              services_path, :class => 'btn btn-default'  %>

<%- model_class = Service -%>
<div class="row" >

  <div class="col-sm-4">

  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
    <dd><%= @service.description %></dd>
    <dt><strong><%= model_class.human_attribute_name(:user_client_id) %>:</strong></dt>
    <dd><%= @service.user_client_id %></dd>
    <dt><strong><%= model_class.human_attribute_name(:user_professional_id) %>:</strong></dt>
    <dd><%= @service.user_professional_id %></dd>
    <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
    <dd><%= @service.status %></dd>
    <dt><strong><%= model_class.human_attribute_name(:photos) %>:</strong></dt>
    <dd><%= @photos.count %></dd>
  </dl>

  </div>

  <div class="col-sm-7 col-offset-1">  

    <div class="page-header">

      <h1>Profissional</h1>
    
    </div>

      <div class="row">

        <div class="col-sm-2">

        <%= image_tag(@service.user_professional.perfil.thumb.url) if @service.user_professional.perfil? %>

        </div>

        <div class="col-sm-7">  

      <ul>
        
        <li><strong>Nome:</strong> <%= @service.user_professional.name%></li>
        <li><strong>E-mail:</strong> <%= @service.user_professional.email%></li>
        <% if @service.user_professional.category!=nil %>
        <li><strong>Categoria:</strong> <%= @service.user_professional.category.name %></li>
        <% else %>
        <li><strong>Categoria:</strong> sem categoria</li>
        <% end %>
      </ul>

        </div>

      </div>

  </div>

<br>
</div>

<% @photos.each do |photo| %>

  <td><%= image_tag(photo.avatar.pic.url) if photo.avatar? %></td>

<% end %>

<br><br><br>

<p> Comentários </p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:service_id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.description %></td>
        <td><%= comment.service_id %></td>
        <td><%= comment.status %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      comment_path(comment), :class => 'btn btn-default btn-xs' %>

          <% if policy(:user).updateComment? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-default btn-xs' %>
          <% end %>

          <% if policy(:user).destroyComment? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <%end%>

          <% service = Service.find_by_id(comment.service_id) %>
          <% if policy(:user).linkReport? and service.user_client_id!=current_user.id %>
              <%= link_to "Denunciar",
                          report_comentario_path(comment.id),
                          :class => 'btn btn-primary btn-xs' %>
          <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<% if policy(:user).createComment? %>
              <%= link_to "Comentar",
                          novo_comentario_path(@service.id),
                          :class => 'btn btn-primary btn-xs' %>
<%end%>

<br><br>

<% if policy(:user).updateService? %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_path(@service), :class => 'btn btn-default' %>
<% end %>

<% if policy(:user).destroyService? %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_path(@service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

<%= will_paginate @comments, renderer: BootstrapPagination::Rails %>

<br><br>