config/routes.rb
Rails.application.routes.draw do

  resources :image_sliders
  resources :sliders
  resources :sobres
  resources :contatos
  resources :image_services

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      },:path => 'u'

  resources :states
  resources :cities
  resources :comments
  resources :services
  resources :users
  resources :categories

  get 'comments/novo/:id', to:'comments#new', as: 'novo_comentario'

  get 'home/index', to:'users#index', as:'mostrar_servico'

  get 'users/show/:id', to:'users#destacar', as:'destacar_usuario'

  get 'users/novo/:id', to:'users#change', as: 'mostrar_usuario'

  get 'users/show', to:'users#desactive', as: 'desactive_usuario'

  get 'comments/report/:id', to:'users#report', as: 'report_comentario'

  #TELA INICIAL - Escolha das cidades
  root to: 'tela_inicial#index'  
  get '/tela_inicial/:alterar', to:'tela_inicial#index', as: 'alterar_cidade'
  
  #TELA DE INICIO - CATEGORIAS, FOTOS, COMENTARIOS
  post 'home', to: 'home#index'
  get 'home', to: 'home#index'
  post 'busca', to: 'home#busca'
  get 'busca/:id', to: 'home#busca', as: "busca_category_id"
  get 'home/professional/:id', to: 'home#show_professional', as: "show_professional"
  get 'home/service/:id', to: 'home#show_service', as: "show_service"

  #PAINEL DO USUARIO
  get 'painel', to: 'painel#index'

  
end

app/models/category.rb
class Category < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	mount_uploader :foto, FotoUploader
	#Status : 0 (Ativo) e 1 (Inativo)
	enum status: [:ativo, :inativo]
	has_many :users
end

app/models/city.rb
class City < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :state
  has_many :users

  def city_state
  	 "#{name} - #{state.name}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :service
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/image_service.rb
class ImageService < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	belongs_to :service

	mount_uploader :avatar, AvatarUploader
end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord
	
	require 'carrierwave/orm/activerecord'

	belongs_to :slider

	mount_uploader :figure, FigureUploader

end

app/models/service.rb
class Service < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :comments, dependent: :destroy
  has_many :image_services, dependent: :destroy
  belongs_to :user_client, class_name: 'User', :foreign_key => 'user_client_id'
  belongs_to :user_professional, class_name: 'User', :foreign_key => 'user_professional_id'

  accepts_nested_attributes_for :image_services, reject_if: :all_blank, allow_destroy: true
end

app/models/slider.rb
class Slider < ApplicationRecord
	has_many :image_sliders, dependent: :destroy

	accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :cities
end

app/models/user.rb
class User < ApplicationRecord

  require 'carrierwave/orm/activerecord'

  mount_uploader :perfil, PerfilUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  enum kind: [:cliente, :professional, :administrator]
  belongs_to :city
  belongs_to :category
  has_many :services



  def active_for_authentication? 
    super && status=='ativo'
    :approved
  end 

  def inactive_message 
    if status=='inativo'
      :not_approved 
    else 
      super
    end 
  end

end

app/controllers/image_sliders_controller.rb
class ImageSlidersController < ApplicationController
  before_action :set_image_slider, only: [:show, :edit, :update, :destroy]

  # GET /image_sliders
  # GET /image_sliders.json
  def index
    @image_sliders = ImageSlider.all
  end

  # GET /image_sliders/1
  # GET /image_sliders/1.json
  def show
  end

  # GET /image_sliders/new
  def new
    @image_slider = ImageSlider.new
  end

  # GET /image_sliders/1/edit
  def edit
  end

  # POST /image_sliders
  # POST /image_sliders.json
  def create
    @image_slider = ImageSlider.new(image_slider_params)

    respond_to do |format|
      if @image_slider.save
        format.html { redirect_to @image_slider, notice: 'Image slider was successfully created.' }
        format.json { render :show, status: :created, location: @image_slider }
      else
        format.html { render :new }
        format.json { render json: @image_slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_sliders/1
  # PATCH/PUT /image_sliders/1.json
  def update
    respond_to do |format|
      if @image_slider.update(image_slider_params)
        format.html { redirect_to @image_slider, notice: 'Image slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_slider }
      else
        format.html { render :edit }
        format.json { render json: @image_slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_sliders/1
  # DELETE /image_sliders/1.json
  def destroy
    @image_slider.destroy
    respond_to do |format|
      format.html { redirect_to image_sliders_url, notice: 'Image slider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_slider
      @image_slider = ImageSlider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_slider_params
      params.require(:image_slider).permit(:figure, :slider_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_sliders_helper.rb
module ImageSlidersHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sobres_helper.rb
module SobresHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/image_sliders/_form.html.erb
<%= form_for(image_slider) do |f| %>
  <% if image_slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_slider.errors.count, "error") %> prohibited this image_slider from being saved:</h2>

      <ul>
      <% image_slider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :slider_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :slider_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:slider_id) %>
  </div>

  <div class="four wide field">
    <%= f.label :figure %><br>
    <%= image_tag(@image_slider.figure_url(:thumb)) if @image_slider.figure? %>
    <%= f.file_field :figure %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_sliders/edit.html.erb
<h1>Editing Image Slider</h1>

<%= render 'form', image_slider: @image_slider %>

<%= link_to 'Show', @image_slider %> |
<%= link_to 'Back', image_sliders_path %>

app/views/image_sliders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Sliders</h1>

<table>
  <thead>
    <tr>
      <th> # </th>
      <th> Slider ID </th>
      <th> Figure </th>
    </tr>
  </thead>

  <tbody>
    <% @image_sliders.each do |image_slider| %>
      <tr>
        <td> <%= image_slider.id %> </td> 
        <td> <%= image_slider.slider_id %> </td> 
        <td><%= image_tag(image_slider.figure.pic.url) if image_slider.figure? %></td>
        <td><%= link_to 'Show', image_slider %></td>
        <td><%= link_to 'Edit', edit_image_slider_path(image_slider) %></td>
        <td><%= link_to 'Destroy', image_slider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Slider', new_image_slider_path %>

app/views/image_sliders/new.html.erb
<h1>New Image Slider</h1>

<%= render 'form', image_slider: @image_slider %>

<%= link_to 'Back', image_sliders_path %>

app/views/image_sliders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_slider_path(@image_slider) %> |
<%= link_to 'Back', image_sliders_path %>