config/routes.rb
Rails.application.routes.draw do

  resources :image_sliders
  resources :sliders
  resources :sobres
  resources :contatos
  resources :image_services

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      },:path => 'u'

  resources :states
  resources :cities
  resources :comments
  resources :services
  resources :users
  resources :categories

  get 'comments/novo/:id', to:'comments#new', as: 'novo_comentario'

  get 'home/index', to:'users#index', as:'mostrar_servico'

  get 'users/show/:id', to:'users#destacar', as:'destacar_usuario'

  get 'users/novo/:id', to:'users#change', as: 'mostrar_usuario'

  get 'users/show', to:'users#desactive', as: 'desactive_usuario'

  get 'comments/report/:id', to:'users#report', as: 'report_comentario'

  #TELA INICIAL - Escolha das cidades
  root to: 'tela_inicial#index'  
  get '/tela_inicial/:alterar', to:'tela_inicial#index', as: 'alterar_cidade'
  
  #TELA DE INICIO - CATEGORIAS, FOTOS, COMENTARIOS
  post 'home', to: 'home#index'
  get 'home', to: 'home#index'
  post 'busca', to: 'home#busca'
  get 'busca/:id', to: 'home#busca', as: "busca_category_id"
  get 'home/professional/:id', to: 'home#show_professional', as: "show_professional"
  get 'home/service/:id', to: 'home#show_service', as: "show_service"

  #PAINEL DO USUARIO
  get 'painel', to: 'painel#index'

  
end

app/models/category.rb
class Category < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	mount_uploader :foto, FotoUploader
	#Status : 0 (Ativo) e 1 (Inativo)
	enum status: [:ativo, :inativo]
	has_many :users
end

app/models/city.rb
class City < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :state
  has_many :users

  def city_state
  	 "#{name} - #{state.name}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :service
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/image_service.rb
class ImageService < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	belongs_to :service

	mount_uploader :avatar, AvatarUploader
end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord
	
	require 'carrierwave/orm/activerecord'

	belongs_to :slider

	mount_uploader :figure, FigureUploader

end

app/models/service.rb
class Service < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :comments, dependent: :destroy
  has_many :image_services, dependent: :destroy
  belongs_to :user_client, class_name: 'User', :foreign_key => 'user_client_id'
  belongs_to :user_professional, class_name: 'User', :foreign_key => 'user_professional_id'

  accepts_nested_attributes_for :image_services, reject_if: :all_blank, allow_destroy: true
end

app/models/slider.rb
class Slider < ApplicationRecord
	has_many :image_sliders, dependent: :destroy

	accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :cities
end

app/models/user.rb
class User < ApplicationRecord

  require 'carrierwave/orm/activerecord'

  mount_uploader :perfil, PerfilUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  enum kind: [:cliente, :professional, :administrator]
  belongs_to :city
  belongs_to :category
  has_many :services



  def active_for_authentication? 
    super && status=='ativo'
    :approved
  end 

  def inactive_message 
    if status=='inativo'
      :not_approved 
    else 
      super
    end 
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :set_city, only: [:index, :busca, :show_professional,  :show_service]
	before_action :set_category, only: [:index, :busca, :show_professional,  :show_service]
	before_action :set_busca, only: [:index, :busca, :show_professional,  :show_service]

	def index
		
		@photos = ImageSlider.all
		@sobre = Sobre.first

		@images_all = ImageService.order("id DESC")

		@images = Array.new

		@images_all.each do |image|
			if image.service.user_professional.city_id == @city.id
				@images.push(image)

				if @images.count>7
					break
				end
			end
		end

		#Usuarios de uma determinada cidade
		#kind: 0(cliente), 1(professional), 2(administrator)
		
		#@users = @q.result().where(kind:1, status: "ativo", destaque: true, city_id: @city)

		@users = @q.result().where(kind:1, status: "ativo", city_id: @city)

		@categories = @users.joins("INNER JOIN categories c ON users.category_id = c.id").select(:category_id).distinct

		@comments = Comment.joins("INNER JOIN services s ON comments.service_id = s.id INNER JOIN users u ON u.id = s.user_professional_id AND u.city_id = #{@city.id} ").order("id DESC").limit(5)

	end

	def busca

		if !params[:id].present?
			
	  		@users = @q.result().where(kind: 1, city_id: @city, status: "ativo")
  		else
  			
  			@users = User.where(category_id: params[:id], city_id: @city, status: "ativo")
  		end
	end

	def show_professional
		@user = User.find_by_id(params[:id])
		@services = Service.where(user_professional_id: @user.id, status: "ativo")
	end
	def show_service
		@service = Service.find_by_id(params[:id].to_i)
		@images = ImageService.where(service_id: @service.id)
		@comments = Comment.where(service_id: @service.id, status: "ativo")
	end
	private
    
    def set_busca
    	@q = User.ransack(params[:q])
    end

    def set_category
    	@categories = Category.joins("INNER JOIN users u ON u.category_id = categories.id AND u.city_id = #{@city.id}")
    end

    def set_city

      	if session[:city_id].present?

      		if params[:id_cidade].present?
      		
      			@city = City.find(params[:id_cidade])
				session[:city_id] = @city.id
      		
      		else
			
				@city = City.find(session[:city_id])
      		
      		end

		else
			if params[:id_cidade].present?
				@city = City.find(params[:id_cidade])
				session[:city_id] = @city.id
			else
				redirect_to root_url
			end
		end
    end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sobres_helper.rb
module SobresHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/busca.html.erb
<div style="padding: 8em 0 0 0;">
<div class="container">
	<div class="row">
   <section class="about" id="service">
        <div class="container">
            <div class="row">
                <h2>Profissionais</h2>
            </div>

        </div>

    </section>
</div>
<div class="row">
<br>
	<div class="row text-center">
		<% @users.each do |u| %>
        
            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%if u.perfil?%>
                        <%= image_tag(u.perfil.pic.url, class: "img-responsive") %>
                                <% else %>
                                <image src="../img/empty.png" class="img-responsive"></image>
                                <% end %>
                    
                    <div class="caption">
                        <h3><%= u.name%></h3>
                        <p>Categoria: <%= u.category.name%></p>
                        <p>
                            <%= link_to "Mais informações", show_professional_path(u), class: "btn btn-primary"%>
                        </p>
                    </div>
                </div>
            </div>
		
		<% end %>
</div>
        </div>
        <!-- /.row -->		
	
</div>
</div>

app/views/home/index.html.erb
<section class="slider" id="home">
        <div class="container-fluid">
            <div class="row">
                <div id="carouselHacked" class="carousel slide carousel-fade" data-ride="carousel">
                    <div class="header-backup"></div>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <% var = 0 %>

                        <% @photos.each do |photo| %>
                        
                            <% if var==0 %>

                                <div class="item active">
                                    <%= image_tag(photo.figure_url(:great)) if photo.figure? %>
                                </div>

                                <% var = var+1 %>

                            <% else %>

                                <div class="item">
                                    <%= image_tag(photo.figure_url(:great)) if photo.figure? %>
                                </div>

                            <% end %>

                        <% end %>

                    </div>
                    <!-- Controls -->
                    <a class="left carousel-control" href="#carouselHacked" role="button" data-slide="prev">
                        <span class="fa fa-arrow-circle-left" aria-hidden="true"></span><
                        <span class="sr-only">Anterior</span>
                    </a>
                    <a class="right carousel-control" href="#carouselHacked" role="button" data-slide="next">
                        <span class="fa fa-arrow-circle-right " aria-hidden="true"></span>>
                        <span class="sr-only">Posterior</span>
                    </a>
                </div>
            </div>
        </div>
    </section><!-- end of slider section -->
    <!-- service section starts here -->
    <section class="service text-center" id="service">
        <div class="container">
            <div class="row">
                <h2>Atividades</h2>
                <h4>Clique em alguma atividade para visualizar os profissionais</h4>

                <% @categories.each do |c| %>

                <div class="col-md-3 col-sm-6">
                    <div class="single-service">
                        
                                <%= link_to busca_category_id_path(c.category_id) do %>
                                <%if c.category.foto?%>
                                <%= image_tag(c.category.foto.pic.url, class: "img-thumbnail img-responsive")%>
                                <% else %>
                                <image src="img/empty.png" class="img-responsive img-thumbnail"></image>
                                <% end %>
    
                                <% end %>
                        <h3 style="margin-top: 0px;"><%= c.category.name%></h3>
                        
                    </div>
                </div>
                <% end %>
               
            </div>
        </div>
    </section><!-- end of service section -->
    <!-- team section -->
    <section class="team" id="team">
        <div class="container">
            <div class="row">
                <div class="team-heading text-center">
                    <h2>Profissionais em destaque</h2>
                    <h4>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</h4>
                </div>
                <% @users.each do |u|%>  
                <% if u.destaque?%>          
                <%= link_to show_professional_path(u) do%>
                <div class="col-md-2 single-member col-sm-4">
                    <div class="person">
                    <%if u.perfil?%>
                        <%= image_tag(u.perfil.pic.url, class: "img-responsive") %>
                                <% else %>
                                <image src="img/empty.png" class="img-responsive"></image>
                                <% end %>
                    
                        
                    </div>
                    <div class="person-detail">
                        <div class="arrow-bottom"></div>
                        <h3><%=u.name%></h3>
                        <p>Atividade: <%= u.category.name %> </p>
                    </div>
                </div>
                <% end %>
                <%end%>
                <% end %>
                              
        </div>
    </section><!-- end of team section -->

    

    <!-- portifolio section -->
    <section class="about" id="protifolio">
        <div class="container">
            <div class="row">
                <h2>Portifolio</h2>
                <h4> Fotos recentes dos serviços executados pelos profissionais</h4>
                <% @images.each do |i|%>
                <a href="#" data-toggle="modal" data-target="#<%= i.id %>">
                <div class="col-md-4 col-sm-6">
                    <div class="single-about-detail clearfix">
                        <div class="about-img">
                            <%= image_tag(i.avatar.url, class: "img-responsive") if i.avatar? %>
                        </div>
                        <div class="about-details">
                            
                            <h3 class="text-center"><%= i.service.description%></h3>
                            <p>
                                Profissional: <%= i.service.user_professional.name%>
                                <br>
                                Cliente: <%= i.service.user_client.name%>
                            </p>
                        </div>
                    </div>
                </div>
                </a>
                 <!-- Modal -->
  <div class="modal fade bs-example-modal-lg" id="<%= i.id%>" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p></p>
          <%= image_tag(i.avatar.url, class: "img-responsive") if i.avatar? %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
      </div>
      
    </div>
  </div>
                <% end %>

                





                
            </div>
        </div>
    </section><!-- end of protifolio section -->

    <!-- about section -->
    <section class="about text-center" id="about">
        <div class="container">
            <div class="row">
                <h2>Sobre</h2>
                <% if @sobre!=nil %>
                    <h3><p> <%= @sobre.description %> </p></h3>
                <% else %>
                    <h3><p> Cadastre um sobre </p></h3>
                <% end %>
                
                
                
            </div>
        </div>
    </section><!-- end of about section -->
    


    <!-- contact section starts here -->
    <section class="service text-center" id="contact">
        <div class="container">
            <div class="row">
                
                    <div class="contact-heading text-center">
                        <h2>Contato</h2>
                    </div>

                    <div class="col-md-5 contact-info text-left">
                        <h3>Informações de contato</h3>
                        <div class="info-detail">
                            <ul><li><i class="fa fa-map-marker"></i><span>Endereço:</span> 123 Some Street , London, UK, CP 123</li></ul>
                            <ul><li><i class="fa fa-phone"></i><span>Telefone:</span> (032) 987-1235</li></ul>
                            <ul><li><i class="fa fa-fax"></i><span>Fax:</span> (123) 984-1234</li></ul>
                            <ul><li><i class="fa fa-envelope"></i><span>Email:</span> <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="7d14131b123d19121e09120f531e1210">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></li></ul>
                        </div>

                        <%= bootstrap_flash%>
                    </div>

                    <% contato = Contato.new %>
                    
                    <%= form_for(contato) do |f| %>

                    <% if contato.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

                              <ul>
                              <% contato.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                    <% end %>

                    <div class="col-md-6 col-md-offset-1 contact-form">

                        <h3>Digite sua mensagem</h3>

                        <form class="form">

                            <div class="name">
                                
                                <%= f.text_field :name, class: "form-control", placeholder: "Nome" %>
                            </div>

                            <div class="email">
                                
                                <%= f.text_field :email, class: "form-control", placeholder: "Email"  %>
                            </div>

                            <div class="phone">
                                
                                <%= f.text_field :phone, class: "form-control", placeholder: "Telefone"  %>
                            </div>

                            <div class="message">
                                
                                <%= f.text_area :message, class: "form-control", placeholder: "Mensagem"  %>
                            </div>

                            <div class="actions">
                                <%= f.submit 'Enviar', :class => 'submit-btn' %>
                            </div><br>

                        </form>
                    </div>

                    <% end %>

                </div>
            
        </div>
    </section><!-- end of contact section -->

app/views/home/show_professional.html.erb
<div style="background: #009999  ; padding: 10em 0 6em 0;">
<div class="container" >
  
	<div class="row">
		  <div class="text-center" >
      
        <center>
        <% if @user.perfil?%>
          <%= image_tag(@user.perfil.pic.url, class: "img-responsive img-circle") %>
                                <% else %>
                                <image src="../../img/empty.png" height="200" width="200" class="img-circle"></image>
                                <% end %>
        
        </center>
        <br>
        <h3 style="color: #fff;">
        <strong>Nome:</strong> <%= @user.name%> - <strong>E-mail:</strong> <%= @user.email%> - <strong>Atividade:</strong> <%= @user.category.name%>
        </h3>
      
      </div>
  </div>
  </div>
  </div>
  <div class="container">
  <div class="row">
      <div class="col-sm-7 col-sm-offset-1">
      <h1>Serviços</h1>
      <hr>
      <% @services.each do |s|%>
      <div class="col-sm-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> <%= s.description%></h4>
                    </div>
                    <div class="panel-body">
                        <h4>
                        Cliente:  <%= s.user_client.name%>
                        </h4>
                        <%= link_to "Mais informações", show_service_path(s), class: "btn btn-primary"%>

                    </div>
                </div>
      </div>
      <% end %>

      </div>
      
            
		
		

        </div>
        <!-- /.row -->		
	
</div>

app/views/home/show_service.html.erb
<div style="padding: 10em 0 6em 0;">
<hr>
<div class="container">
<!-- portifolio section -->
    <section class="about" id="protifolio">
        <div class="container">
            <div class="row">
                <h2><%= @service.description%></h2>
                <h4> Fotos do serviço do cliente: <%= @service.user_client.name%> </h4>
                <% @images.each do |i|%>
                <a href="#" data-toggle="modal" data-target="#<%= i.id %>">
                <div class="col-md-4 col-sm-6">
                    <div class="single-about-detail clearfix">
                        <div class="about-img">
                            <%= image_tag(i.avatar.url, class: "img-responsive") if i.avatar? %>
                        </div>
                        
                    </div>
                </div>
                </a>
                 <!-- Modal -->
  <div class="modal fade bs-example-modal-lg" id="<%= i.id%>" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p></p>
          <%= image_tag(i.avatar.url, class: "img-responsive") if i.avatar? %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
      </div>
      
    </div>
  </div>
                <% end %>

                





                
            </div>
        </div>
    </section><!-- end of protifolio section -->
</div>
<div class="container">
  <h3><span class="glyphicon glyphicon-comment"></span> Comentários</h3>
            
            <% @comments.each do |c|%>  
              <div class="row">
              <div class="col-sm-1" style="margin: 1.5em 0 0 1em ;">
                <%= image_tag(@service.user_client.perfil.thumb.url, class: "img-responsive") if @service.user_client.perfil? %>
                <% if !@service.user_client.perfil?%>
                <image src="../../img/empty.png" height="60px"></image>
                <% end %>
              </div>
              <div class="col-sm-9">
                  <h3>
                    <strong>
                      <%=@service.user_client.name%> - <%= c.created_at.strftime("%d/%m/%Y, %H:%M")%>
                    </strong>
                  </h3>                
                  <h4>
                    <em>
                      <%= c.description%>
                    </em>
                  </h4>
                
              </div>
        </div>
            
            <% end %>
            
            
</div>
</div>