config/routes.rb
Rails.application.routes.draw do

  resources :image_sliders
  resources :sliders
  resources :sobres
  resources :contatos
  resources :image_services

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      },:path => 'u'

  resources :states
  resources :cities
  resources :comments
  resources :services
  resources :users
  resources :categories

  get 'comments/novo/:id', to:'comments#new', as: 'novo_comentario'

  get 'home/index', to:'users#index', as:'mostrar_servico'

  get 'users/show/:id', to:'users#destacar', as:'destacar_usuario'

  get 'users/novo/:id', to:'users#change', as: 'mostrar_usuario'

  get 'users/show', to:'users#desactive', as: 'desactive_usuario'

  get 'comments/report/:id', to:'users#report', as: 'report_comentario'

  #TELA INICIAL - Escolha das cidades
  root to: 'tela_inicial#index'  
  get '/tela_inicial/:alterar', to:'tela_inicial#index', as: 'alterar_cidade'
  
  #TELA DE INICIO - CATEGORIAS, FOTOS, COMENTARIOS
  post 'home', to: 'home#index'
  get 'home', to: 'home#index'
  post 'busca', to: 'home#busca'
  get 'busca/:id', to: 'home#busca', as: "busca_category_id"
  get 'home/professional/:id', to: 'home#show_professional', as: "show_professional"
  get 'home/service/:id', to: 'home#show_service', as: "show_service"

  #PAINEL DO USUARIO
  get 'painel', to: 'painel#index'

  
end

app/models/category.rb
class Category < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	mount_uploader :foto, FotoUploader
	#Status : 0 (Ativo) e 1 (Inativo)
	enum status: [:ativo, :inativo]
	has_many :users
end

app/models/city.rb
class City < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :state
  has_many :users

  def city_state
  	 "#{name} - #{state.name}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  belongs_to :service
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/image_service.rb
class ImageService < ApplicationRecord
	require 'carrierwave/orm/activerecord'

	belongs_to :service

	mount_uploader :avatar, AvatarUploader
end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord
	
	require 'carrierwave/orm/activerecord'

	belongs_to :slider

	mount_uploader :figure, FigureUploader

end

app/models/service.rb
class Service < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :comments, dependent: :destroy
  has_many :image_services, dependent: :destroy
  belongs_to :user_client, class_name: 'User', :foreign_key => 'user_client_id'
  belongs_to :user_professional, class_name: 'User', :foreign_key => 'user_professional_id'

  accepts_nested_attributes_for :image_services, reject_if: :all_blank, allow_destroy: true
end

app/models/slider.rb
class Slider < ApplicationRecord
	has_many :image_sliders, dependent: :destroy

	accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  has_many :cities
end

app/models/user.rb
class User < ApplicationRecord

  require 'carrierwave/orm/activerecord'

  mount_uploader :perfil, PerfilUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Status : 0 (Ativo) e 1 (Inativo)
  enum status: [:ativo, :inativo]
  enum kind: [:cliente, :professional, :administrator]
  belongs_to :city
  belongs_to :category
  has_many :services



  def active_for_authentication? 
    super && status=='ativo'
    :approved
  end 

  def inactive_message 
    if status=='inativo'
      :not_approved 
    else 
      super
    end 
  end

end

app/controllers/image_services_controller.rb
class ImageServicesController < ApplicationController
  before_action :set_image_service, only: [:show, :edit, :update, :destroy]

  # GET /image_services
  # GET /image_services.json
  def index
    @image_services = ImageService.all
  end

  # GET /image_services/1
  # GET /image_services/1.json
  def show
  end

  # GET /image_services/new
  def new
    @image_service = ImageService.new
  end

  # GET /image_services/1/edit
  def edit
  end

  # POST /image_services
  # POST /image_services.json
  def create
    @image_service = ImageService.new(image_service_params)

    respond_to do |format|
      if @image_service.save
        format.html { redirect_to @image_service, notice: 'Image service was successfully created.' }
        format.json { render :show, status: :created, location: @image_service }
      else
        format.html { render :new }
        format.json { render json: @image_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_services/1
  # PATCH/PUT /image_services/1.json
  def update
    respond_to do |format|
      if @image_service.update(image_service_params)
        format.html { redirect_to @image_service, notice: 'Image service was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_service }
      else
        format.html { render :edit }
        format.json { render json: @image_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_services/1
  # DELETE /image_services/1.json
  def destroy
    @image_service.destroy
    respond_to do |format|
      format.html { redirect_to image_services_url, notice: 'Image service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_service
      @image_service = ImageService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_service_params
      params.require(:image_service).permit(:avatar, :service_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_services_helper.rb
module ImageServicesHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sobres_helper.rb
module SobresHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/image_services/_form.html.erb
<%= form_for(image_service) do |f| %>
  <% if image_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_service.errors.count, "error") %> prohibited this image_service from being saved:</h2>

      <ul>
      <% image_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :service_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :service_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:service_id) %>
  </div>

  <div class="four wide field">
    <%= f.label :avatar %><br>
    <%= image_tag(@image_service.avatar_url(:thumb)) if @image_service.avatar? %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_services/edit.html.erb
<h1>Editing Image Service</h1>

<%= render 'form', image_service: @image_service %>

<%= link_to 'Show', @image_service %> |
<%= link_to 'Back', image_services_path %>

app/views/image_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Services</h1>

<table>
  <thead>
    <tr> 
      <th> Service ID </th>
      <th> Photo </th>
    </tr>
  </thead>

  <tbody>

    <% @image_services.each do |image_service| %>

      <tr>

      <td> <%= image_service.service_id %> </td> 

      <td><%= image_tag(image_service.avatar.pic.url) if image_service.avatar? %></td>

        <td><%= link_to 'Show', image_service %></td>
        <td><%= link_to 'Edit', edit_image_service_path(image_service) %></td>
        <td><%= link_to 'Destroy', image_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Service', new_image_service_path %>

app/views/image_services/new.html.erb
<h1>New Image Service</h1>

<%= render 'form', image_service: @image_service %>

<%= link_to 'Back', image_services_path %>

app/views/image_services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_service_path(@image_service) %> |
<%= link_to 'Back', image_services_path %>